greeting:
  message: "hello"
'%test':
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        driver: org.h2.Driver
        url: jdbc:h2:mem:H2DB;INIT=RUNSCRIPT FROM 'classpath:scripts/carga_testes.sql'
      password: sa
      username: sa
'%dev':
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:      
        url: jdbc:postgresql://localhost:5432/apiEmpresa
        max-size: 16
      password: postgres54
      username: postgres
quarkus:
  smallrye-openapi:
    path: /swagger
  swagger-ui:
    always-include: true
    path: /explore
  hibernate-orm:
    log:
      sql: true
    database:
      generation: update
  http:    
    cors:
       ~: true
       methods: GET,PUT,POST,DELETE, OPTIONS
       origins: 'http://localhost:4200'        
  log:
    level: INFO
microprofile:
  rest:
    client:
      disable:
        default:
          mapper: false
java:
  util:
    logging:
      manager: org.jboss.logmanager.LogManager
